### ISSUE TITLE
undefined: "github.com/mikespook/golib/signal".Loop

### ISSUE THREAD

**Issue by xingskycn** [mikespook/gearman-go#57]
kentchentekiiMac-23868:gearman kentchen$ go run s1.go
# command-line-arguments
./s1.go:73: undefined: "github.com/mikespook/golib/signal".Loop

**Comment by mikespook** [comment]
I redesigned API of the package `golib/signal` recently that method `Loop` has been changed into `Wait`.
It will be OK after you upgrade the codes.
