### ISSUE TITLE
Race condition on close worker

### ISSUE THREAD

**Issue by zainulbr** [mikespook/gearman-go#88]
hi All, i got race condition on calling close worker function. i was try worker code example, but race condition reproduced also.o.
```
zainul@zainul-bahar:~/Documents/GOPATH/src/github.com/mikespook/gearman-go/example/worker$ ./worker 
2019/05/27 13:30:48 Starting ...
^C==================
WARNING: DATA RACE
Read at 0x00c0000aa210 by main goroutine:
  github.com/mikespook/gearman-go/worker.(*Worker).Close()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/worker.go:223 +0x7f
  main.main()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/example/worker/worker.go:74 +0x78f

Previous write at 0x00c0000aa210 by goroutine 8:
  github.com/mikespook/gearman-go/worker.(*Worker).Work()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/worker.go:200 +0x5e

Goroutine 8 (running) created at:
  main.main()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/example/worker/worker.go:71 +0x704
==================
2019/05/27 13:30:52 read tcp4 127.0.0.1:41870->127.0.0.1:4730: use of closed network connection
==================
WARNING: DATA RACE
Write at 0x00c0000ae0a8 by main goroutine:
  github.com/mikespook/gearman-go/worker.(*agent).Close()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/agent.go:128 +0xd3
  github.com/mikespook/gearman-go/worker.(*Worker).Close()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/worker.go:225 +0xdf
  main.main()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/example/worker/worker.go:74 +0x78f

Previous read at 0x00c0000ae0a8 by goroutine 7:
  github.com/mikespook/gearman-go/worker.(*agent).disconnect_error()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/agent.go:114 +0x42
  github.com/mikespook/gearman-go/worker.(*agent).work()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/agent.go:63 +0x4b5

Goroutine 7 (running) created at:
  github.com/mikespook/gearman-go/worker.(*agent).Connect()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/agent.go:42 +0x5f7
  github.com/mikespook/gearman-go/worker.(*Worker).Ready()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/worker/worker.go:178 +0x139
  main.main()
      /home/zainul/Documents/GOPATH/src/github.com/mikespook/gearman-go/example/worker/worker.go:67 +0x64d
==================
2019/05/27 13:30:52 Shutdown complete!
Found 2 data race(s)
```

**Comment by galihrivanto** [comment]
it seem adding synchronization on `disconnect_error` solve the issue

```go
func (a *agent) disconnect_error(err error) {
	a.Lock()
	defer a.Unlock()

	if a.conn != nil {
		err = &WorkerDisconnectError{
			err:   err,
			agent: a,
		}
		a.worker.err(err)
	}
}
```

**Comment by zainulbr** [comment]
ok thanks mr @galihrivanto,
example should update also
direct call close function still reproduce race


`package main

import (
	"log"
	"net"
	"os"
	"strings"
	"time"

	"github.com/mikespook/gearman-go/client"
	"github.com/mikespook/gearman-go/worker"
	"github.com/mikespook/golib/signal"
)

func ToUpper(job worker.Job) ([]byte, error) {
	log.Printf("ToUpper: Data=[%s]\n", job.Data())
	data := []byte(strings.ToUpper(string(job.Data())))
	return data, nil
}

func ToUpperDelay10(job worker.Job) ([]byte, error) {
	log.Printf("ToUpper: Data=[%s]\n", job.Data())
	time.Sleep(10 * time.Second)
	data := []byte(strings.ToUpper(string(job.Data())))
	return data, nil
}

func Foobar(job worker.Job) ([]byte, error) {
	log.Printf("Foobar: Data=[%s]\n", job.Data())
	for i := 0; i < 10; i++ {
		job.SendWarning([]byte{byte(i)})
		job.SendData([]byte{byte(i)})
		job.UpdateStatus(i+1, 100)
	}
	return job.Data(), nil
}

func main() {
	log.Println("Starting ...")
	defer log.Println("Shutdown complete!")
	w := worker.New(worker.Unlimited)
	
	defer func() {
		cli, err := client.New("tcp4", "127.0.0.1:4730")
		if err != nil {
			log.Println(err)
			return
		}

		log.Println("shutdown")
		cli.Do("Closure-x", make([]byte, 0), client.JobHigh, func(resp *client.Response) {
			log.Println("close")
		})

	}()

	w.ErrorHandler = func(e error) {
		log.Println(e)
		if opErr, ok := e.(*net.OpError); ok {
			if !opErr.Temporary() {
				proc, err := os.FindProcess(os.Getpid())
				if err != nil {
					log.Println(err)
				}
				if err := proc.Signal(os.Interrupt); err != nil {
					log.Println(err)
				}
			}
		}
	}
	w.JobHandler = func(job worker.Job) error {
		log.Printf("Data=%s\n", job.Data())
		return nil
	}
	w.AddServer("tcp4", "127.0.0.1:4730")
	w.AddFunc("Foobar", Foobar, worker.Unlimited)
	w.AddFunc("ToUpper", ToUpper, worker.Unlimited)
	w.AddFunc("ToUpperTimeOut5", ToUpperDelay10, 5)
	w.AddFunc("ToUpperTimeOut20", ToUpperDelay10, 20)
	w.AddFunc("SysInfo", worker.SysInfo, worker.Unlimited)
	w.AddFunc("MemInfo", worker.MemInfo, worker.Unlimited)
	w.AddFunc("Closure-x", func(job worker.Job) ([]byte, error) {
		log.Println("requesting close")
		w.Close()
		return nil, nil
	}, worker.OneByOne)

	if err := w.Ready(); err != nil {
		log.Fatal(err)
		return
	}
	go w.Work()
	signal.Bind(os.Interrupt, func() uint { return signal.BreakExit })
	signal.Wait()
}
`

**Comment by sadlil** [comment]
@galihrivanto can please open a PR?

**Comment by galihrivanto** [comment]
sure #89
